image: Visual Studio 2017

install:
  - dotnet tool install --global fpublisher-cli

build_script:
  - cmd: fpublisher --run-ci

environment:
  nuget_api_key:
    secure: uxeBhnDDyowaBY1oDNFPo9Yz9wbJUWwAw8BgagEbHtKLQR3uxOADA7dvO+pcANt0
